version: "3.5"

services:
  mwe-db:
    image: postgres:12.2-alpine
    container_name: mwe-db
    restart: always
    ports:
      - 5432:5432
    networks:
      - mwexpress
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mwedb123
      POSTGRES_USER: mwe
      POSTGRES_DB: mwedb

  mwe-db-ui:
    image: adminer
    container_name: mwe-db-ui
    restart: always
    ports:
      - 8080:8080
    networks:
      - mwexpress
    depends_on:
      - mwe-db
    environment:
      ADMINER_DEFAULT_SERVER: "mwe-db"
      ADMINER_PLUGINS: "enum-types"

  mwe-logs:
    image: datalust/seq:2020.2.4593
    container_name: mwe-logs
    ports:
    - 5341:80
    networks:
      - mwexpress
    environment:
      ACCEPT_EULA: Y
      
  mwexpress:
    image: docker.pkg.github.com/alisentas/mwexpress/mwexpress
    container_name: mwexpress
    networks:
      - mwexpress
    depends_on:
      - mwe-db
      - mwe-logs
    environment:
      DB_CONNECTION_STRING: "postgresql://mwe:mwedb123@mwe-db:5432/mwedb"
      TELEGRAM_API_KEY: "API_KEY_HERE"
      SEQ_LOG_HOST: "mwe-logs"
      START_TIME: "00:01"
      END_TIME: "23:59"

      
networks:
  mwexpress:
    name: mwexpress
    driver: bridge

volumes:
  log_data:
    driver: local
  db_data:
    driver: local